data:
  # Specify as "host:port"
  address: localhost
  port: 3306

  # The name of the database to store tournament data
  # - This must be created already.
  database: minecraft

  # Credentials for the database.
  username: root
  password: ''

  # The prefix for all TournamentManager SQL tables.
  table_prefix: 'tm_'
  
team:
   # Only applies when players use /tm team <teamname> join
   maxsize: 2
  
signs:
   prefix:  '&lTournament'
   ready:   '&a&lReady!'
   waiting: '&6&lWaiting...'
  
debug: false