main: com.atlshearer.tournamentmanager.TournamentManager
name: TournamentManager
version: 0.2.0
api-version: 1.15
author: atlshearer
description: An Example plugin

depend: [TNTRun_reloaded]

commands:
    tournamentmanager:
        description: Tournament Manager Command
        usage: /tm <command> <args>
        aliases: [tm]